### PR TITLE
an easy way to restart without refactoring the entire codebase

### PR DESCRIPTION
**Pull request by khanghugo**
Pressing Tab twice to restart (with new contents too). If you press something when you press Tab for the first time, it will exit.

It's not a bug, it's a feature.

### CODE REVIEW

**Comment by max-niederman** [comment]
This is exactly the same as the current behavior just with different bindings. What exactly is better about using tab than escape?

**Comment by khanghugo** [comment]
I did not see the Escape KeyEvent so I did not know there was a key for that.

But, that Escape is not really restart. It is to end the test. Just some minor changes in this commit will actually restart (and can help quit the program). Also Tab is easier to press and doesn't need you to move your wrist far enough. 

If that is too bad then Tab as a replacement for R for restarting is still more convenient on the hand.

**Comment by khanghugo** [comment]
Anyway, I just came up with a solution that makes Tab restarts test on one press. It just came up.

**Comment by max-niederman** [comment]
It's not really intuitive to press tab to restart, which I think is more important than the tiny amount of time saved. I may be wrong, but I don't think many users are restarting over and over again.

**Comment by khanghugo** [comment]
It's the default behavior on Monkey Type so I thought it would be helpful.

But anyway, I did make this commits that #29 is asking for
https://github.com/khanghugo/ttyper/commit/d14589a585d9012c350c69f68ba153a8b3041858

**Pull request closed without merging**
