### PR TITLE
add: wordlists of portuguese with 200, 1000 lines and advanced…

### PR DESCRIPTION
**Pull request by mdxv**
This PR integrates wordlists of 200, 1000, and advanced Portuguese words. This will significantly expand the variety of words available to users, promoting a more diverse and challenging typing experience.

### CODE REVIEW

**Review by max-niederman — CHANGES_REQUESTED** [review]
Would you mind adding these to the table of languages in the readme?

**Comment by mdxv** [comment]
> Would you mind adding these to the table of languages in the readme?

Absolutely! I'll get that done right away

**Review by max-niederman — CHANGES_REQUESTED** [review]
Oh, one other thing. I didn't notice this before, but you're using `portuguese_advanced` wheras we're currently using hyphens for existing language variants. Could you just rename the file to use hyphens real quick?

**Comment by mdxv** [comment]
> Oh, one other thing. I didn't notice this before, but you're using `portuguese_advanced` wheras we're currently using hyphens for existing language variants. Could you just rename the file to use hyphens real quick?

Done 👍

**Comment by mdxv** [comment]
Do I need to do anything to get this PR to be merged? 🤔

**Review by max-niederman — APPROVED** [review]
Sorry about that! I just forgot.

**Pull request merged**
