### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by fnordpig**
Hi!  I'm looking to (at least in a fork) integrate GPT3.5 and DALL-E to generate sentences with a theme and character set and display ascii art pictures to help my daughter (who loves minecraft) get more into the experience.  I'd like to rev up the versions and thought it would be useful to submit back.

### CODE REVIEW

**Comment by fnordpig** [comment]
I updated to use ratatui as tui was abandoned and forked into an org owned by the community and renamed.

**Comment by max-niederman** [comment]
Thanks for the help with updating dependencies. I think it's _probably_ out of scope of ttyper to add support for generative AI, although I'm considering adding some kind of quote sourcing in v2 (#83). You can probably get that working pretty easily by just writing a shell script which wraps ttyper and passes the sentences in a file or through stdin.

For ASCII art though, I'm not sure that enough people would want it for it to be worth the added complexity. How exactly do you envision the feature would work?

**Comment by fnordpig** [comment]
Here are the diff: https://github.com/max-niederman/ttyper/compare/main...fnordpig:ttyper:generative_ai
But note that I made no meaningful attempt to integrate smoothly, so I basically short circuit the existing Opt entirely and go off the hard coded stuff for now.  If it serves any purpose I'll work to make it play nicer with the rest of the code, but at this point my goal is to teach my daughter typing :-)

**Comment by fnordpig** [comment]
Here's with DALL-E images rendered inline:
image

**Comment by max-niederman** [comment]
That's great! I'm happy you're able to adapt ttyper for teaching your daughter.

**Pull request merged**
